// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinerViewer.Context;

#nullable disable

namespace MinerViewer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220831181313_migr")]
    partial class migr
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("MinerViewer.Data.Entities.GraphicCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cooler")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HotSpotTemp")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MemoryTemp")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MinerId");

                    b.ToTable("GraphicCards");
                });

            modelBuilder.Entity("MinerViewer.Data.Entities.Miner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Coin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Os")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Miners");
                });

            modelBuilder.Entity("MinerViewer.Data.Entities.MinerAdress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MinerAdresses");
                });

            modelBuilder.Entity("MinerViewer.Data.Entities.GraphicCard", b =>
                {
                    b.HasOne("MinerViewer.Data.Entities.Miner", null)
                        .WithMany("Cards")
                        .HasForeignKey("MinerId");
                });

            modelBuilder.Entity("MinerViewer.Data.Entities.Miner", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
